Updated project to use Pytube instead of youtube-dl
* [API] Pytube download test task

* [API] Added support for pytube downloader

* [WEB] Changed endpoint path in API to client info endpoint

* [API] Modified exception handlers passing to main FastAPI instance.

* Fix for HTTP 410 Gone error in pytube - update of pytube library to latest

* [API] Fixed unittests for pytube integration

* Moved pytest and coverage options to pyproject.toml

* Moved tests outside of main package

* [API] Changed way of fetching version

* [API] Moved exception handlers to seperate modules.

* [WEB] Web app refactor to use redux (unfinished)

* [WEB] Adding getDownloadsList method for fetching list of dowloaded medias from API

* [WEB] Application refactor (unfinished)

* [API] Added mypy

* [API] Added get downloads endpoint.

* [API] Code formatting

* [API] Added dev scripts

* [API] Added ConfZ for settings managment, started API refactor.

* Refactored version endpoint, refactored schemas

* Updated pytest version

* Added mocked persisted download fixture

* Refactored endpoint for fetching available video download parameters

* Fixing config test an fetch downloads test

* Added isort configuration in pyproject.toml

* Added downloading media using Pytube library

* Updated testing options

* Sorted imports

* Added additional dev scripts

* Added submit download endpoint

* Added SSE on status update callback endpoint

* Added endpoint for fetching downloaded file

* Refactored enpoint for deleting downloaded media

* pytest script generate html coverage

* Uvicorn update, added script for running devserver

* Fixed ImportError: cannot import name '_unicodefun' from 'click' error by updating black to latest version

* Code formatting for backend part of project

* [API] Refactored logic related to client ID persistence.

* [API] Updated user persistence logic to comply with different cross site configurations.

* Added camelCase responses in API

* [WEB] Updating dependencies

* Fixed useeffect loading

* [API] Fixed Internal Server Error wehen fetching preview data

* Removed unused components. Deleted will be replaced with MUI components

* Fixed build error for API Docker image

* Added MUI, removed no longer needed libraries

* Replaced icons on MUI icons, added first UI version of Preview component for downloaded media

* Fix typo in datasource.py

* Fixed empty videoStreams in case of https://www.youtube.com/watch?v=17jbCUR4IeQ

* Frontend APP refactor to make use of MUI library

* Refactor tests for API

* Added delete method for datasource and fixed exception when submitting new download

* Fixed typo in donwload status enum name

* Deta sdk update

* Removed InMemoryDatabase implementation

* Fixed few tests

* Fixed unittests

* Added useContext for LoadingContext

* Initial refactor for MediaItem

* Bumping version from 0.1.0 to 0.2.0

* Bumping version from 0.2.0 to 0.3.0-alpha.0

* TODOs

* Fixed bug  in /download/stream endpoint: stream response should contain camelCase JSON

* Added download porcess spinner

* Improved logging in exception handlers

* Fixed download media button

* Added field date_submitted to download model

* Added support for timestamp fields when download is submitted, started downloading, downloaded, downloaded by client, deleted

* Bumping version from 0.3.0-alpha.0 to 0.3.0-alpha.1

* Fixed some mypy warning and errors

* isort apply

* Exclude file_path in JSON response

* Moved App.jsx to repo root

* Version bump up

* Improved responsivity for download list

* [API] Fixed HTTP 500 when provideing invalid URL

* Add handling of 422 in preview endpoint

* Show toast when download is deleted

* Clear search prompt on preview fetching

* Add link button to original video in download preview

* Version bump up

* Fixed duration display on media item card

* Refactor Donwload response schema

* mypy update

* isort

* Small refactor

* Added pre-commit

* fixed API tests

* Added docker-compose.yaml in api root

* Added README.md for API

* Added README.md for web

* Added main README.md file

* README fix

* Small fix .env.example

* Changed name of env variables in .env.example